###
POST http://127.0.0.1:8020/auth/login/ 
Content-Type: application/json 

{
    "username":"admin",
    "password":"123"
}

###
POST http://127.0.0.1:8000/auth/login/refresh/ 
Content-Type: application/json 

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NDY4NTMwNCwiaWF0IjoxNzYyMDkzMzA0LCJqdGkiOiI5NzRjN2IyZjNjZTU0MDNkYjc0NTU0Mjg4MjM5MDdjNyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.-jYqYy7A25IzJtnp4rIpitHjnDs8b8Be8uL7QpZkzr0" 
}
 
###
POST http://127.0.0.1:8020/auth/register/
Content-Type: application/json 

{
    "username":"admin2",
    "first_name": "Nur mamun",
    "password":"123",
    "email":"anmamun0@gmail.com"
}

###
GET  http://127.0.0.1:8020/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDkwNDYwLCJpYXQiOjE3NjM0ODU2NjAsImp0aSI6IjZhZGZjMDg3MWVjMTQ4Mzc5YWM1MzM0MWIyNjM5NGNhIiwidXNlcm5hbWUiOiJhZG1pbiJ9.jaf7ihP2rzjuZn28ji9_2C3gHMAmAQYRZfJSt6T0BGw
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com"  
}


###
POST http://127.0.0.1:8000/auth/password/change/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzY1ODMxLCJpYXQiOjE3NjIxNjEwMzEsImp0aSI6ImFjY2RlOTU2NDg4ZjQ3N2M4Yzc5NjIwZDkwN2E1YjM4IiwidXNlcm5hbWUiOiJhZG1pbiJ9.kCOGJWmBQF_stf2fYIqiOwvn_zE3Ml8-n4CPTZwZBKk
Content-Type: application/json 

{  
  "old_password": "123",  
  "new_password": "123"  
}


###
POST http://127.0.0.1:8020/auth/email/verify/request/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com"  
}

###
POST http://127.0.0.1:8000/auth/email/verify/conform/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzc5MzQyLCJpYXQiOjE3NjIxNzQ1NDIsImp0aSI6IjM3Mzc2M2FkNDlkYjRkNTE5MGU2OTIxNGU0OTY0MjdlIiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOjE1LCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.z0cD8SCd1htD-gOanduyHFXqleOyj5P03X7VOeTljxY
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com",  
  "otp": "642179"  
}

// Celery windows Run: celery -A core worker --loglevel=INFO -P solo  


###
POST http://127.0.0.1:8000/auth/password/forgot/otp/request/
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com" 
}

###
POST http://127.0.0.1:8000/auth/password/forgot/otp/conform/
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com",
  "otp": "714642" 
}

###
POST http://127.0.0.1:8000/auth/password/forgot/reset/",
Content-Type: application/json 

{  
  "email": "anmamun0@gmail.com",
  "otp": "714642",
  "new_password": "00a00@asdDED" 
}


# -----------------Inventory App----------------------------------


# --------------------------
# Category urls
# --------------------------
###
GET http://127.0.0.1:8020/category/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NDIwODk4LCJpYXQiOjE3NjM4MTYwOTgsImp0aSI6Ijg0MDhjZmM1MWExZTRmMTI5Y2EzYjUyY2FlYjMzOGQ2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.3nERzWwKPq6P85MJj5ClNE98RaGs80KGOhuLlny-s00

###
GET http://127.0.0.1:8020/category/661c05cc-4041-4248-8cbf-fd00c18473f7/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE

###
POST http://127.0.0.1:8020/category/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
Content-Type: application/json 

{  
  "name": "Alu (edit)"  
}

###
PATCH  http://127.0.0.1:8020/category/c0958cad-0afb-4a6d-8e98-fc28ca75c9ba/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
Content-Type: application/json 

{  
  "name": "Alu (edit)"  
}

###
DELETE http://127.0.0.1:8020/category/94369ba8-8197-463b-b7e7-969977dc82a3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
 

# --------------------------
# Inventory urls
# --------------------------
###
GET http://127.0.0.1:8020/inventory/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NDIwODk4LCJpYXQiOjE3NjM4MTYwOTgsImp0aSI6Ijg0MDhjZmM1MWExZTRmMTI5Y2EzYjUyY2FlYjMzOGQ2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.3nERzWwKPq6P85MJj5ClNE98RaGs80KGOhuLlny-s00


###
GET http://127.0.0.1:8020/inventory/5d00929a-3ce0-4b8f-b773-5b332cba1cc1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NDIwODk4LCJpYXQiOjE3NjM4MTYwOTgsImp0aSI6Ijg0MDhjZmM1MWExZTRmMTI5Y2EzYjUyY2FlYjMzOGQ2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.3nERzWwKPq6P85MJj5ClNE98RaGs80KGOhuLlny-s00

###
PATCH http://127.0.0.1:8020/inventory/751a58fc-bfa8-4d6a-9dd7-5cbdb23f8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NDIwODk4LCJpYXQiOjE3NjM4MTYwOTgsImp0aSI6Ijg0MDhjZmM1MWExZTRmMTI5Y2EzYjUyY2FlYjMzOGQ2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.3nERzWwKPq6P85MJj5ClNE98RaGs80KGOhuLlny-s00
Content-Type: application/json 

{  
    "name": "B"
}
###
PATCH  http://127.0.0.1:8020/inventory/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
Content-Type: application/json 

{  
    "name": "PHone - 13", 
}

###
DELETE http://127.0.0.1:8020/inventory/5d00929a-3ce0-4b8f-b773-5b332cba1cc1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDQ1NTYwLCJpYXQiOjE3NjI0NDA3NjAsImp0aSI6IjE4OWM4MDIzYmQxNzQyNDg4Nzg3ZWQ4NmQ2YTNjOGM5IiwidXNlcm5hbWUiOiJhZG1pbjEwIiwiaWQiOiIyMzhiMGZlYi02YTBhLTQ0M2YtOGJkNS0wMWM0NTljYzlkNmEiLCJlbWFpbCI6ImFubWFtdW4wQGdtYWlsLmNvbSIsImlzX3Bob25lX3ZlcmlmeSI6ZmFsc2UsImlzX2VtYWlsX3ZlcmlmeSI6ZmFsc2V9.zGcOCc7lusPltLJNpBxPTaWXyuMSjUhR9oM7ywrxYkE
 



# ----------------------------
# ShareMe Model
# ----------------------------

###
GET  http://127.0.0.1:8020/share/inventory/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTYwODAyLCJpYXQiOjE3NjM1NTYwMDIsImp0aSI6ImZmNjg5MGYzYWQ2MzQ3ZThiZWQzNzdiNmM0MjM0NTk2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.xDkgcWuYxi_B0-nLM_io7bsZv40EoHrNuP4_OuLLzNk
Content-Type: application/json 

{  
    "shared_user": "admin4" 
}

# -----------------------
# Websocket testing
# -----------------------
# ws://localhost:8020/ws/inventory/<username>/

### admin
PATCH  http://127.0.0.1:8020/inventory/52d37c63-7607-4208-a261-24b626f008a8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDYzMTgyLCJpYXQiOjE3NjM0NTgzODIsImp0aSI6IjllN2I3ZmJhYjE5NDQzMGNhN2ZkYmE0OWVmZDhlMDJkIiwidXNlcm5hbWUiOiJhZG1pbiJ9.1Z-A8wWxKArPJCBJVka6OxutIaJExce6_q7MYzMozYo
Content-Type: application/json 

{  
    "name": "A",
    "priority": "High", 
    "number": 2, 
    "category": "369391e7-9e60-4cfa-b589-566be124d116"  
}

### admin1
PATCH  http://127.0.0.1:8020/inventory/751a58fc-bfa8-4d6a-9dd7-5cbdb23f8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDYzMzM5LCJpYXQiOjE3NjM0NTg1MzksImp0aSI6ImFmODE0N2U1OWJjNzQ0YTQ5NjE5YTA1ZDQxY2QwNmEwIiwidXNlcm5hbWUiOiJhZG1pbjEifQ.DIQGhb7bXoOim670xYtUYqwTyCitpaUa81uyy6aPv_4
Content-Type: application/json 

{  
    "name": "B",
    "priority": "High", 
    "number": 2, 
    "category": "369391e7-9e60-4cfa-b589-566be124d116"  
}

### admin4
PATCH  http://127.0.0.1:8020/inventory/b98b5b7e-406b-4a51-85a1-7d135661748f/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDYzNDE3LCJpYXQiOjE3NjM0NTg2MTcsImp0aSI6IjFlNWQ5YzE3NzEwODRkZTU5MGQ1ZDUyYjllZjI2ODAzIiwidXNlcm5hbWUiOiJhZG1pbjQifQ.rQKviJ9e8hiOG2wCj8EfITdFGw16pdz5nPQB9lLS5s4
Content-Type: application/json 

{  
    "name": "Y",
    "priority": "High", 
    "number": 2, 
    "category": "369391e7-9e60-4cfa-b589-566be124d116"  
}


### admin5
PATCH  http://127.0.0.1:8020/inventory/fb4b1ace-082d-42f1-9230-2d2e2a032e37/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MDYzNDY2LCJpYXQiOjE3NjM0NTg2NjYsImp0aSI6ImVlM2ZmNzMwYjU4ODRlODc4YzMxZTQyNTdhODUxNjMzIiwidXNlcm5hbWUiOiJhZG1pbjUifQ.c51RpGN5Gatoe48IGZR31aPudMMPeHLMnIwC9ZKFyo8
Content-Type: application/json 

{  
    "name": "Z",
    "priority": "High", 
    "number": 2, 
    "category": "369391e7-9e60-4cfa-b589-566be124d116"  
}