# Generated by Django 5.2.7 on 2025-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_subscriptionplan_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="connetion_limits",
            field=models.IntegerField(default=0),
        ),
    ]
