# Generated by Django 5.2.7 on 2025-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_transaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("expired", "Expired")],
                max_length=20,
                null=True,
            ),
        ),
    ]
