# Generated by Django 5.2.7 on 2025-11-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_alter_usersubscription_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usersubscription",
            name="per_user_single_subscription_active",
        ),
    ]
